import { useState } from "react";
import DashboardLayout from "../components/DashboardLayout";
import { Card } from "../components/ui/card";
import { Button } from "../components/ui/button";
import { Zap, CheckCircle, Clock, Search, Network, FileText, AlertTriangle, ChevronRight, Bot } from "lucide-react";

const alerts = [
  { id: "AML-2026-0471", entity: "Account #CA-4471", type: "Structuring", score: 97 },
  { id: "AML-2026-0469", entity: "Global Trade Corp", type: "Network Anomaly", score: 92 },
  { id: "AML-2026-0468", entity: "Viktor Sokolov", type: "PEP Match", score: 88 },
];

type StepStatus = "pending" | "running" | "done";

const investigationSteps = [
  { id: "kyc", icon: Search, label: "KYC Data Retrieval", desc: "Fetching customer profile, documents, and verification history" },
  { id: "watchlist", icon: AlertTriangle, label: "Watchlist Query", desc: "Cross-referencing OFAC, UN, EU Consolidated, PEP databases" },
  { id: "graph", icon: Network, label: "Entity Graph Mapping", desc: "Tracing 3-degree network relationships and fund flows" },
  { id: "brief", icon: FileText, label: "Investigation Brief", desc: "Generating AI-cited report with regulatory context" },
];

const sampleBrief = `AUTONOMOUS INVESTIGATION BRIEF
Alert ID: AML-2026-0471 · Generated by NexusAI Agent v2.4

EXECUTIVE SUMMARY
Account #CA-4471 has exhibited classic structuring behavior, with three transactions of $49,800 each (total: $149,400) executed within a 48-hour window — deliberately keeping amounts below the CA$50,000 FINTRAC reporting threshold. This pattern is consistent with "smurfing" as defined under PCMLTFA s.5(1).

KEY FINDINGS
[1] KYC Profile: Account opened November 2023. Owner entity: unmarked shell company registered in Ontario. UBO not fully disclosed. Risk score elevated to 85 at onboarding.

[2] Watchlist: No direct OFAC match. Partial PEP association through linked director (87% name-match, pending human confirmation). Cross-reference with EU Consolidated List — no confirmed hit.

[3] Network Graph: Account #CA-4471 is connected to 3 additional accounts (Shell LLC A, Corp B, Trust Acct C) that have received inbound transfers within the same 48-hour window, forming a 4-node collection ring.

[4] Transaction Pattern: All three structuring transactions were initiated from the same IP subnet (10.122.x.x), consistent with coordinated automated behavior rather than organic client activity.

RECOMMENDED ACTION
File Suspicious Transaction Report (STR) with FINTRAC under PCMLTFA s.7. Freeze account pending senior compliance review. Open linked-entity case for Shell LLC A, Corp B, and Trust Acct C.

CITATIONS
[1] FINTRAC Guideline 2: Suspicious Transactions — Indicators of Structuring
[2] PCMLTFA s.7 — Mandatory Reporting Threshold
[3] FATF Recommendation 20 — Suspicious Transaction Reports`;

export default function AgentInvestigator() {
  const [selectedAlert, setSelectedAlert] = useState(alerts[0]);
  const [running, setRunning] = useState(false);
  const [stepStatuses, setStepStatuses] = useState<Record<string, StepStatus>>({});
  const [briefReady, setBriefReady] = useState(false);
  const [ttd, setTtd] = useState<string | null>(null);

  const runAgent = () => {
    setRunning(true);
    setBriefReady(false);
    setStepStatuses({});
    const start = Date.now();

    const delays = [400, 1200, 2200, 3400];
    investigationSteps.forEach((step, i) => {
      setTimeout(() => {
        setStepStatuses(prev => ({ ...prev, [step.id]: "running" }));
      }, delays[i]);
      setTimeout(() => {
        setStepStatuses(prev => ({ ...prev, [step.id]: "done" }));
        if (i === investigationSteps.length - 1) {
          setBriefReady(true);
          setRunning(false);
          const elapsed = ((Date.now() - start) / 1000).toFixed(1);
          setTtd(elapsed);
        }
      }, delays[i] + 700);
    });
  };

  const getStepStatus = (id: string): StepStatus => stepStatuses[id] || "pending";

  return (
    <DashboardLayout pageTitle="Agentic Investigator" breadcrumb="Autonomous AI">
      <div className="flex gap-4 h-[calc(100vh-130px)]">

        {/* Left: Alert Selection */}
        <div className="w-[260px] flex-shrink-0 flex flex-col gap-3">
          <div className="text-[0.6rem] font-bold uppercase tracking-widest text-[var(--text-purple-3)] font-['Geist_Mono'] px-1">Select Alert to Investigate</div>
          {alerts.map(a => (
            <div
              key={a.id}
              onClick={() => { setSelectedAlert(a); setStepStatuses({}); setBriefReady(false); setTtd(null); setRunning(false); }}
              className={`p-3.5 rounded-xl border-[0.5px] cursor-pointer transition-all ${selectedAlert.id === a.id ? "border-[var(--border-purple)] bg-[var(--glass2)]" : "border-[var(--border)] bg-[var(--glass)] hover:border-[var(--border2)]"}`}
            >
              <div className="flex items-center gap-2 mb-1.5">
                <AlertTriangle className="w-3.5 h-3.5 text-[var(--coral)] flex-shrink-0" />
                <span className="text-xs font-semibold text-white truncate">{a.entity}</span>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-[0.62rem] text-[var(--text-purple-3)] font-['Geist_Mono']">{a.id}</span>
                <span className="text-[0.65rem] font-bold text-[var(--coral)] font-['Geist_Mono']">{a.score}</span>
              </div>
              <div className="text-[0.62rem] text-[var(--text-purple-2)] mt-1">{a.type}</div>
            </div>
          ))}

          <Button
            className="gradient-purple text-white border-none gap-2 mt-2"
            onClick={runAgent}
            disabled={running}
          >
            <Bot className="w-4 h-4" />
            {running ? "Agent Running..." : "Launch AI Agent"}
          </Button>

          {ttd && (
            <div className="p-3 bg-[rgba(52,211,153,.06)] border-[0.5px] border-[rgba(52,211,153,.2)] rounded-lg text-center">
              <div className="text-[0.6rem] text-[var(--text-purple-3)] font-['Geist_Mono'] uppercase mb-1">Time to Decision</div>
              <div className="text-xl font-bold text-[var(--teal)] font-['Instrument_Serif']">{ttd}s</div>
              <div className="text-[0.6rem] text-[var(--text-purple-3)] mt-0.5">vs. ~4hrs manual review</div>
            </div>
          )}
        </div>

        {/* Center: Agent Pipeline */}
        <div className="w-[280px] flex-shrink-0 flex flex-col gap-3">
          <div className="text-[0.6rem] font-bold uppercase tracking-widest text-[var(--text-purple-3)] font-['Geist_Mono'] px-1">Agent Pipeline</div>

          <Card className="glass-2 border-[0.5px] border-[var(--border)] p-4 flex-shrink-0">
            <div className="flex items-center gap-2 mb-3 pb-3 border-b-[0.5px] border-[var(--border)]">
              <div className={`w-2 h-2 rounded-full ${running ? "bg-[var(--brand-hi)] animate-pulse" : briefReady ? "bg-[var(--teal)]" : "bg-[var(--text-purple-3)]"}`} />
              <span className="text-xs font-bold font-['Geist_Mono'] text-[var(--text-purple-2)]">
                {running ? "INVESTIGATING" : briefReady ? "COMPLETE" : "STANDBY"}
              </span>
              <span className="ml-auto text-[0.6rem] text-[var(--text-purple-3)]">{selectedAlert.id}</span>
            </div>

            <div className="space-y-3">
              {investigationSteps.map((step, i) => {
                const status = getStepStatus(step.id);
                const Icon = step.icon;
                return (
                  <div key={step.id} className="flex items-start gap-3 relative">
                    {i < investigationSteps.length - 1 && (
                      <div className="absolute left-[13px] top-7 w-[1px] h-[calc(100%-4px)] bg-[var(--border)]" />
                    )}
                    <div className={`w-7 h-7 rounded-lg flex items-center justify-center flex-shrink-0 transition-all ${status === "done" ? "bg-[rgba(52,211,153,.15)] border-[0.5px] border-[rgba(52,211,153,.3)]" : status === "running" ? "bg-[var(--brand-glow)] border-[0.5px] border-[var(--border-purple)] animate-pulse" : "bg-[var(--glass)] border-[0.5px] border-[var(--border)]"}`}>
                      {status === "done"
                        ? <CheckCircle className="w-3.5 h-3.5 text-[var(--teal)]" />
                        : status === "running"
                          ? <Icon className="w-3.5 h-3.5 text-[var(--brand-hi)]" />
                          : <Icon className="w-3.5 h-3.5 text-[var(--text-purple-3)] opacity-50" />
                      }
                    </div>
                    <div>
                      <div className={`text-xs font-semibold ${status === "done" ? "text-white" : status === "running" ? "text-[var(--brand-hi)]" : "text-[var(--text-purple-3)]"}`}>
                        {step.label}
                      </div>
                      <div className="text-[0.62rem] text-[var(--text-purple-3)] mt-0.5 leading-tight">{step.desc}</div>
                    </div>
                    {status === "running" && (
                      <Clock className="w-3 h-3 text-[var(--brand-hi)] ml-auto mt-0.5 animate-spin flex-shrink-0" />
                    )}
                  </div>
                );
              })}
            </div>
          </Card>

          {briefReady && (
            <Card className="glass-2 border-[0.5px] border-[rgba(52,211,153,.2)] p-4 bg-[rgba(52,211,153,.04)]">
              <div className="flex items-center gap-2 text-[var(--teal)] text-xs font-bold mb-2">
                <CheckCircle className="w-3.5 h-3.5" /> Brief Ready for Review
              </div>
              <p className="text-[0.65rem] text-[var(--text-purple-2)]">Agent completed investigation in {ttd}s. SAR draft and recommended actions are ready.</p>
              <Button size="sm" className="gradient-purple text-white text-xs h-7 gap-1.5 mt-3 w-full">
                <ChevronRight className="w-3 h-3" /> File SAR from Brief
              </Button>
            </Card>
          )}
        </div>

        {/* Right: Investigation Brief */}
        <div className="flex-1 flex flex-col gap-3 overflow-hidden">
          <div className="text-[0.6rem] font-bold uppercase tracking-widest text-[var(--text-purple-3)] font-['Geist_Mono'] px-1">Investigation Brief</div>
          <Card className="glass-2 border-[0.5px] border-[var(--border)] flex-1 overflow-hidden flex flex-col">
            <div className="px-5 py-3 border-b-[0.5px] border-[var(--border)] flex items-center justify-between bg-[var(--glass)]">
              <div className="flex items-center gap-2 text-[0.7rem] font-bold font-['Geist_Mono'] tracking-wider uppercase text-[var(--text-purple-2)]">
                <Zap className="w-3.5 h-3.5 text-[var(--brand-hi)]" /> AI-GENERATED BRIEF
              </div>
              {briefReady && (
                <span className="text-[0.6rem] text-[var(--teal)] font-['Geist_Mono'] font-bold flex items-center gap-1">
                  <CheckCircle className="w-2.5 h-2.5" /> CITED · FINTRAC-ALIGNED
                </span>
              )}
            </div>
            <div className="flex-1 overflow-y-auto p-5 bg-[var(--bg)]">
              {briefReady ? (
                <pre className="text-[0.72rem] text-[var(--text-purple)] font-['Geist_Mono'] leading-relaxed whitespace-pre-wrap">{sampleBrief}</pre>
              ) : (
                <div className="h-full flex items-center justify-center flex-col gap-3">
                  <Bot className="w-10 h-10 text-[var(--text-purple-3)] opacity-40" />
                  <p className="text-[var(--text-purple-3)] text-sm text-center">
                    {running ? "Agent is gathering evidence..." : "Select an alert and launch the AI agent to generate an autonomous investigation brief."}
                  </p>
                  {running && (
                    <div className="flex gap-1.5">
                      {[0, 1, 2].map(i => (
                        <div key={i} className="w-1.5 h-1.5 rounded-full bg-[var(--brand-hi)] animate-bounce" style={{ animationDelay: `${i * 0.15}s` }} />
                      ))}
                    </div>
                  )}
                </div>
              )}
            </div>
          </Card>
        </div>
      </div>
    </DashboardLayout>
  );
}
